Practica/WebApplication1/Controllers/AltaUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Practica.Models;

namespace Practica.Controllers
{
    public class AltaUsuariosController : Controller
    {
        // GET: AltaUsuarios
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Guardar(UsuarioViewModel user)
        {
            try
            {
                // Si el formulario es válido
                if (ModelState.IsValid)
                {

                    if (ConfigurationManager.AppSettings["almacenamiento"] == "persistente")
                    {
                        // Base de datos
                        using (EntityCrud db = new EntityCrud())
                        {
                            var usuario = new usuario();
                            usuario.Email = user.Email;
                            usuario.Nombre = user.Nombre;
                            usuario.Password = user.Password;

                            db.usuario.Add(usuario);
                            db.SaveChanges();
                        }
                    }
                    else if (ConfigurationManager.AppSettings["almacenamiento"] == "volatil")
                    {
                        // Almacenamiento en sesión
                        List<UsuarioViewModel> listaUsuarios;

                        if(Session["Usuarios"]!= null)
                        {
                            listaUsuarios = Session["Usuarios"] as List<UsuarioViewModel>;
                        }
                        else
                        {
                            listaUsuarios = new List<UsuarioViewModel>();
                        }
                        listaUsuarios.Add(user);
                        Session["Usuarios"] = listaUsuarios;
                    }
                    
                    // Redirige al listado de usuarios
                    return Redirect("/Home/Listado");
                }
                
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
            return Redirect("/AltaUsuarios");
        }
    }
}

Practica/WebApplication1/Views/AltaUsuarios/Index.cshtml
@model Practica.Models.UsuarioViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Alta de Usuarios</h2>
<div>
    @using (Html.BeginForm("Guardar", "AltaUsuarios", FormMethod.Post))
    {
        <p>
            @Html.LabelFor(m => m.Nombre)
            @Html.TextBoxFor(m => m.Nombre, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Nombre, "", new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(m => m.Edad)

            @Html.TextBoxFor(i => i.Edad, new { @type = "number" })
            @Html.ValidationMessageFor(m => m.Edad, "", new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(m => m.Password)
            @Html.PasswordFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
        </p>
        <div>
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>

    }
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>